site_name: My Docs
site_url: https://confusingblank.github.io/confusingblank.github.io/
theme:
  name: material
  palette:
    scheme: slate
    primary: grey
nav:
  - Home: index.md
  - Crdential Dumping: Credential_Dumping.md
