site_name: Zenitram Wiki
site_url: https://squidfunk.github.io/wiki/
theme:
  name: material
  palette:
    scheme: slate
    primary: grey
nav:
  - Home: index.md
  - Crdential Dumping: Credential_Dumping.md
  - Malware Dev: malwaredev/payload-testing.md
