site_name: Zenitram Wiki
site_url: https://confusingblank.github.io/
theme:
  name: material
  palette:
    scheme: slate
    primary: grey
nav:
  - Home: index.md
  - Crdential Dumping: Credential_Dumping.md
  - Malware Dev:
    - Payload Testing Snippets: malwaredev/payload-testing.md
    - PE Format Essentials: malwaredev/pe-file-format.md
