site_name: Security Wiki
site_url: https://confusingblank.github.io/
theme:
  name: material
  palette:
    scheme: slate
    primary: grey
nav:
  - Home: index.md
  - Windows Exploitation:
    - Crdential Dumping: windowsexploitation/credential-dumping.md
    - Lateral Movement: windowsexploitation/lateral-movement.md
  - Malware Dev:
    - Payload Testing Snippets: malwaredev/payload-testing.md
    - PE Format Essentials: malwaredev/pe-file-format.md
