site_name: Security Wiki
site_url: https://confusingblank.github.io/
theme:
  name: material
  palette:
    scheme: slate
    primary: white
  features:
    - navigation.tabs
    - navigation.top
nav:
  - Home: index.md
  - OSINT:
    - Subdomain Enumeration: OSINT/subdomain-enumeration.md
  - Web App Testing:
    - Chrome DevTools: web-app/chrome-dev-tools.md
  - Windows Exploitation:
    - Crdential Dumping: windowsexploitation/credential-dumping.md
    - Kerberos: windowsexploitation/kerberos.md
    - Lateral Movement: windowsexploitation/lateral-movement.md
    - Persistence: windowsexploitation/persistence.md
    - Privilege Escalation: windowsexploitation/privilege-escalation.md
  - Malware Dev:
    - Payload Testing Snippets: malwaredev/payload-testing.md
    - PE Format Essentials: malwaredev/pe-file-format.md
